### ISSUE TITLE
Upgrade for picking up items on the ground

### ISSUE THREAD

**Issue by deadspidervenom** [bl4ckscor3/UnnamedSculkMod#10]
Suggestion 2
------
Vacuum Upgrade

A upgrade to can apply to an emitter, transmitter or receiver. It would gather up items on the ground in a radius around it
+++

**Comment by bl4ckscor3** [comment]
We've decided to implement this feature in a restricted manner, not having it available as an upgrade. We feel this is a bit too out of scope for the mod, and can be implemented by using other mods like Vacuum Hoppers in conjunction with the sculk barrel.
Instead, we decided to make the sculk emitter automatically pick up items that are above it, if there is no sculk barrel below. This will be helpful for instance in a farm's drop collection area.
