### ISSUE TITLE
Allow emitter to be placed on the barrel's sides

### ISSUE THREAD

**Issue by deadspidervenom** [bl4ckscor3/UnnamedSculkMod#9]
Suggestion
------
Allow the emitter to be placed on any sides of the storage block (or barrel) and have it rotate. One reason is top side of storage blocks is needed by mods like "create" for the chutes and has no alternative, also some build designs might want the emitter hidden but the barrel shown.
+++

**Comment by bl4ckscor3** [comment]
Implemented in 66f11886c08318098d1c2d12bc245c4d972ceb61. All three sculk item transporters can now be placed on all sides.
We will release an update with this and other fixes & improvements in the very near future.
